"""flashcard fk removed from user

Revision ID: f0e1c9804995
Revises: 4a3c1e8c77a4
Create Date: 2024-08-16 18:54:21.353379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0e1c9804995'
down_revision: Union[str, None] = '4a3c1e8c77a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
